version: "3.8"

services:
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres: 
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"

  redis:
      image: redis:7.4.2-alpine
      restart: always
      env_file: .env
      volumes:
        - redis_data:/data
      ports:
        -  "6379:6379"
      command:
        - redis-server
   
volumes:
  postgres_data:
  redis_data:
