# @name GET_ME

GET http://localhost:8000/api/v1/users/me
Content-Type:application/json
x-authorization:"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImhhdHN1bmUubWlrdUBnbWFpbC5jb20iLCJleHAiOjE3NDIwNzUzNzZ9.QqPK1Jw2oYYujdGAq0RQq1nRsnBXc924Rr7DmyTs-8uHD5U-HWUYVNdfYDPI_gY87f4WmwKgifnD7MEwrkhwnDn06IgnpZlnTE_4o7GxVHUorRN-i3wQR3UMUuJe1Z2KgDWPvO931DxC82Et6K73eYFapLbi8dNDt8eL0gopetzFoA6fOf-BzHo3H44_pnI3VhqZnTakzgqo59QufF6fqLokMhXNrx-YzVCiOfezHfa96Esa_c-f-rzLm3d-BTN6EJ7i8d9vJiqzDUxlo7rWpK7rIArY0hAumyLZdc21rV775pHBkeZxUBavG_4HdpEXOxpBf25egb-GPYj06DweFVzSHlj-nY9i-vp3rGLXpTjIfy3stMDxt0dHuXFWw0fZcv6q-t5z0gxhYfKWqQMHS3NFYTPCatqvmoEcQql34W5D5_wDY_ErqMSWBd7hHr7btaLJJ8-_KKfhtLDcX6d5G2ZTTDeBVnN_ax3zHEokGSVzbHOom6ycnj1IyvQ7qIZFCVt3UaiVEvSW2qLiuDt_iZIL_c1LLorNm0RIFsPnbQXEENwB3H9Gy3jTmMNIz-IvZwEAgrinkbnDMABdu0QU8WjSiCWzz_tcL9f9Ck2IgqGBP3XWIzQ0pWcCgFR-I45-w7ZVWPsPD7ZBE1MKadQyW8GIG2A_dJjorHY2qjgj8z0
x-client-id:1

