# @name LOGOUT

POST http://localhost:8000/api/v1/auths/logout
Content-Type:application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMCwiZW1haWwiOiJoYXRzdW5lLm1pa3VAZ21haWwuY29tIiwiZXhwIjoxNzQyMDUxNjA5fQ.mqilwa8vv-CK4jPO9EsOl_QOoYEqsCQH9MJqrrCDfYibZYgm8-iSYayXUygvcUpuL0GBz6yfZDsMTk4BlkK1BKLUc9Z9PAUhOdZaIosO3LKLScQ9zOKNoXpjmqnkwA897_gNYvydueIsQ1EYUzrV65ZIjrbRHv9jSTg83u_iXqevLc260_g1zC7_UXDMDhkwY3F0-FfOVg8Y1ZFSDeia2TeKyktcigCe4OUgGQ76uWSGW0w7YXBogDv18SYSxgXi78vVoR7PMgw5v-C74YrdPJqHyXDB67Csc84ey1Q8a3iJ0FMFxuzrH4MlfkF2rMAJbj4Is6eZ11Bv0HMPXz0EVIK6VI9H2E1C6Ah-cwNH3eqIlpqi7sKwy-vdUxE3Qk-xG4x4jGN3inUa-S_SiTOhgnJ6GyLu_jiHjaTRaANpbsaEKJU6psTnhiEQf7xDF7v8tMoN9zQ7S0fRe7vHBq50GyXSEoxWDmUexzU8oqJS0kbBnc9KFRjofVba_mOjcVdpZLLPa4ZGirng3jDlGFYE3t1_1tqe9mglgf3IHcfX1KqwQEnWcpmRRGs-uxVae03Fds-aNmBWcqyYGmszb2fhKF0t1XxsLBIFXKEkZi70lMiVB6IqLBLShOZBsd-7AZCYbhjHmWEuAqqOfgU8G7LNbWdlhhLebueysY2y2iSpjPE
x-client-id:20

